@BodyProcessing
Feature: Promobox transforms

  Promo-boxes act as a platform for many kinds of elements displayed alongside paragraphs including as asides,
  summaries, lists, related content etc. Selected promo-box "types" are transformed according to the editorial intent
  based on "clues" in the Methode markup (i.e. a class).

Scenario Outline: Promo-box transforms
  When it is transformed, <methodeXml> becomes <contentXml>

Examples:
  | methodeXml | contentXml |
# copied from bodyprocessingrule.feature
  | <promo-box class="numbers-component"><table width="170px" align="left" cellpadding="6px"><tr><td><promo-headline><p class="title">£350M</p></promo-headline></td></tr><tr><td><promo-intro><p>The cost of eating at Leon and Tossed every single day.</p></promo-intro></td></tr></table></promo-box> | <big-number><big-number-headline><p>£350M</p></big-number-headline><big-number-intro><p>The cost of eating at Leon and Tossed every single day.</p></big-number-intro></big-number> |
  | <promo-box align="left"><table align="left" cellpadding="6px" width="170px"><tr><td><promo-title><p><a href="http://www.ft.com/reports/ft-500-2011" title="www.ft.com">FT 500</a></p></promo-title></td></tr><tr><td><promo-headline><p>Headline</p></promo-headline></td></tr><tr><td><promo-image fileref="/FT/Graphics/Online/Secondary_%26_Triplet_167x96/2011/06/SEC_ft500.jpg?uuid=432b5632-9e79-11e0-9469-00144feabdc0"/></td></tr><tr><td><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro></td></tr><tr><td><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"/></p></promo-link></td></tr></table></promo-box> | <promo-box><promo-title><p><a href="http://www.ft.com/reports/ft-500-2011" title="www.ft.com">FT 500</a></p></promo-title><promo-headline><p>Headline</p></promo-headline><promo-image><content data-embedded="true" id="432b5632-9e79-11e0-0a0f-978e959e1689" type="http://www.ft.com/ontology/content/ImageSet"></content></promo-image><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"></a></p></promo-link></promo-box> |
  | <promo-box align="left"><table align="left" cellpadding="6px" width="170px"><tr><td><promo-title><p><a href="http://www.ft.com/reports/ft-500-2011" title="www.ft.com">FT 500</a></p></promo-title></td></tr><tr><td><promo-headline><p>Headline</p></promo-headline></td></tr><tr><td><web-master xtransform="scale(0.1538 0.1538)" tmx="2048 1152 315 177" width="2048" height="1152" fileref="/FT/Graphics/Online/Master_2048x1152/Martin/butterfly-2048x1152.jpg?uuid=432b5632-9e79-11e0-9469-00144feabdc0" dtxInsert="Web Master" id="U112075852229295"/></td></tr><tr><td><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro></td></tr><tr><td><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"/></p></promo-link></td></tr></table></promo-box> | <promo-box><promo-title><p><a href="http://www.ft.com/reports/ft-500-2011" title="www.ft.com">FT 500</a></p></promo-title><promo-headline><p>Headline</p></promo-headline><promo-image><content data-embedded="true" id="432b5632-9e79-11e0-0a0f-978e959e1689" type="http://www.ft.com/ontology/content/ImageSet"></content></promo-image><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"></a></p></promo-link></promo-box> |
# KH add check that body processing rules are applied to promo-title
  | <promo-box align="left"><table align="left" cellpadding="6px" width="170px"><tr><td><promo-title><p id="U10501125990059gOC"><span class="bullet">Keep track of disruption<br align="block"></br><br align="block"></br></span></p><p><a href="http://www.firstgreatwestern.co.uk/disruption" title="www.firstgreatwestern.co.uk"></a><foo><bar/></foo> Arriva reported on Sunday that much of the weekendÆs earlier flood-related problems on trains from Cardiff were resolved, although there were delays. Updates are listed on: <b><a href="http://www.journeycheck.com/arrivatrainswales" target="_blank" title="www.journeycheck.com">www.journeycheck.com<br align="block"></br>/arrivatrainswales</a></b></p><p><b><author-name>Caroline Binham</author-name></b></p></promo-title></td></tr><tr><td><promo-headline><p>Headline</p></promo-headline></td></tr><tr><td><web-master xtransform="scale(0.1538 0.1538)" tmx="2048 1152 315 177" width="2048" height="1152" fileref="/FT/Graphics/Online/Master_2048x1152/Martin/butterfly-2048x1152.jpg?uuid=432b5632-9e79-11e0-9469-00144feabdc0" dtxInsert="Web Master" id="U112075852229295"/></td></tr><tr><td><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro></td></tr><tr><td><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"/></p></promo-link></td></tr></table></promo-box> | <promo-box><promo-title><p>Keep track of disruption<br/><br/></p><p> Arriva reported on Sunday that much of the weekendÆs earlier flood-related problems on trains from Cardiff were resolved, although there were delays. Updates are listed on: <strong><a href="http://www.journeycheck.com/arrivatrainswales" title="www.journeycheck.com">www.journeycheck.com<br/>/arrivatrainswales</a></strong></p><p><strong>Caroline Binham</strong></p></promo-title><promo-headline><p>Headline</p></promo-headline><promo-image><content data-embedded="true" id="432b5632-9e79-11e0-0a0f-978e959e1689" type="http://www.ft.com/ontology/content/ImageSet"></content></promo-image><promo-intro><p>The risers and fallers in our annual list of the world’s biggest companies</p></promo-intro><promo-link><p><a href="http://www.ft.com/cms/s/0/0bdf4bb6-6676-11e4-8bf6-00144feabdc0.html"></a></p></promo-link></promo-box> |
# New related-item test cases
# NB the expected contentXml was authored by Simon Gibbs manually, except for image set UUIDs which were edited to match output (i.e. they were "ignored")
# Jill Ward's description "a complex "related-article" class created by dragging one story into another (a Sidebar)"
  | <promo-box channel="FTcom" align="right" class="related-article"><table cellpadding="4px" width="156px" align="right"><tr><td align="left"><promo-title><p>Complex related article</p></promo-title></td></tr><tr><td align="left"><promo-headline><a dtxInsert="Sidebar - right aligned" href="/FT/Content/World%20News/Stories/Hold/testpromobox_sidebar.xml?uuid=fbbee07f-5054-4a42-b596-64e0625d19a6"><p>Story headline</p></a></promo-headline></td></tr><tr><td><web-master height="84" id="U1160975182135Y8F" tmx="2048 1152 150 84" width="150" xtransform="scale(0.07324 0.07324)" fileref="/FT/Graphics/Online/Master_2048x1152/2015/08/MAS_grannychic.jpg?uuid=965648a8-4226-11e5-b98b-87c7270955cf"/></td></tr><tr><td align="left"><promo-intro><p>Long standfirst</p></promo-intro></td></tr></table></promo-box> | <related id="fbbee07f-5054-4a42-b596-64e0625d19a6" type="http://www.ft.com/ontology/content/Article"><title>Complex related article</title><headline>Story headline</headline><media><content data-embedded="true" id="965648a8-4226-11e5-27ed-105dfd7dfe86" type="http://www.ft.com/ontology/content/ImageSet"></content></media><intro><p>Long standfirst</p></intro></related> |
# JW: "a basic "related-article" type created using the "Promo-box - Master image_LEFT" component"
  | <promo-box channel="FTcom" align="left" class="related-article"> &lt; <table cellpadding="6px" width="170px" align="left"><tr><td><promo-title><p>Basic related article title</p></promo-title></td></tr><tr><td><promo-headline><p><a shape="rect" href="http://www.ft.com" popupwindowsize="normal">Typed headline with ft.com link</a></p></promo-headline></td></tr><tr><td><web-master height="84" id="U1160975182135JOE" width="150"/></td></tr><tr><td><promo-intro><p>Here is some description text that the editor has typed.</p></promo-intro></td></tr></table> &gt; </promo-box> | <related url="http://www.ft.com"><title>Basic related article title</title><headline>Typed headline with ft.com link</headline><intro><p>Here is some description text that the editor has typed.</p></intro></related> |
# JW: "a "related-item" containing a link to a FT.com URL that's pasted in (ie: a "In Depth" promo)"
  | <promo-box class="related-item" align="left">&lt;<table cellpadding="6px" width="170px" align="left"><tr><td><promo-title><p>In depth</p></promo-title></td></tr><tr><td><promo-headline><p><a title="The shooting down of MH17 in depth - FT.com" href="http://www.ft.com/indepth/malaysia-airlines-flight-mh17">Malaysia Airlines Flight MH17</a></p></promo-headline></td></tr><tr><td><promo-image tmx="167 96 167 96" fileref="/FT/Graphics/Online/Secondary_%26_Triplet_167x96/2014/07/452327156_20140720094530.jpg?uuid=966e00b8-0ff2-11e4-80b1-00144feabdc0"/></td></tr><tr><td><promo-intro><p>News and analysis on the shooting down of Malaysia Airlines Flight MH17 by a missile over eastern Ukraine<br/><br/><a href="http://www.ft.com/indepth/malaysia-airlines-flight-mh17">Further reading</a></p></promo-intro></td></tr></table>&gt;</promo-box> | <related url="http://www.ft.com/indepth/malaysia-airlines-flight-mh17"><title>In depth</title><headline>Malaysia Airlines Flight MH17</headline><media><content data-embedded="true" id="966e00b8-0ff2-11e4-1ed7-978e959e1689" type="http://www.ft.com/ontology/content/ImageSet"></content></media><intro><p>News and analysis on the shooting down of Malaysia Airlines Flight MH17 by a missile over eastern Ukraine<br/><br/><a href="http://www.ft.com/indepth/malaysia-airlines-flight-mh17">Further reading</a></p></intro></related> |